### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by choijungp** [developer0hye/Things_Of_Yonghye#2]
Hi, i am jungin,, I read your write. I was surprised. Because of Swings........

Maybe I have to say goodbye,,,,

**Comment by choijungp** [comment]
If you have the time, please leave me an answer.

**Comment by developer0hye** [comment]
KKKKKKKKKKKKKKKKKKK

Hey jjang!!

You are so cute KKKKKKKKKKKKKKKKKK
